<a href="https://colab.research.google.com/github/ginaazambrano/IA2023-2GINA_ZAMBRANO/blob/main/actividad_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import numpy as np and see the version

# your code here
#pass
import numpy as np

In [2]:
# Create a 1D array of numbers from 0 to 9
# your code here
#pass
a = np.random.randint(0,9, size=(1,9))
print (a)

[[0 5 4 2 4 8 1 6 8]]


In [3]:
# Create random vector of size 10 and replace the maximum value by 0
#pass
vector= np.random.randint(0,101, size=10)
print("Vector original:")
print(vector)
indice_maximo=np.argmax(vector)
vector[indice_maximo] = 0
print("Vector con el máximo valor reemplazado por O:")
print(vector)


Vector original:
[38 39 16 20 29 11 53 82 43 85]
Vector con el máximo valor reemplazado por O:
[38 39 16 20 29 11 53 82 43  0]


In [4]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
#pass
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
number=arr[1,2]
print("Numero o from the array:", number)

Numero o from the array: 8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
#pass
arr=np.array([1,2,3,4,5,6,7])
numer=arr[2:5]
print("numero impreso:", numer)

numero impreso: [3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
#pass
arr=np.array([1,2,3,4,5,6,7])
numer=arr[-4:]
print("numero impreso:", numer)

numero impreso: [4 5 6 7]


In [7]:
# Create a 3×3 numpy array of all True’s
# your code here
#pass
matriz= np.ones((3,3), dtype=bool)
print("matriz 3*3")
print(matriz)


matriz 3*3
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extract all odd numbers from arr
# your code here
#pass
arr = np.array([1,2,3,4,5,6,7,8,9])
odd_number=arr[arr % 2 !=0]
print("numeros impares:", odd_number)

numeros impares: [1 3 5 7 9]


In [9]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
#pass
vector = np.arange(10,50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Reverse a vector (first element becomes last)
#pass
vector=np.array([1,2,3,4,5])
vector_revertido = vector[::-1]
print(vector)


[1 2 3 4 5]


In [11]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
#pass
matriz = np.random.randint(0,101, size=(10,10))
print("Matriz de  10*10 valores enteros aleatorios:")
print(matriz)

valor_minimo=np.min(matriz)
valor_maximo=np.max(matriz)
print("Valor nínimo en la matriz:", valor_minimo)
print("Valor máximo en la matriz:", valor_maximo)

Matriz de  10*10 valores enteros aleatorios:
[[62 25 40 41 45 31  1 33 46 69]
 [88 45 84 17 79 19 54 38 29 40]
 [95 69 23  6 22 79 93 20 34  5]
 [34 23 40 62 25 25 27 92 91 51]
 [17  5 85  5 67 82  3 97  9 20]
 [ 6 94 63 78 65 75 82 10 53  8]
 [92 29 29 59  6 16 31 26 75 47]
 [59 96 46 46  3 37 10 84  1 35]
 [53 78 59 74 89 54  8 40 54 65]
 [61 75 61 78 32 16 71  9 46  3]]
Valor nínimo en la matriz: 1
Valor máximo en la matriz: 97


In [12]:
# Create a 3x3x3 array with random values
#pass
matriz_tridimensional = np.random.random((3, 3, 3))
print("Matriz tridimensional 3x3x3 con valores aleatorios:")
print(matriz_tridimensional)

Matriz tridimensional 3x3x3 con valores aleatorios:
[[[0.42670885 0.07859803 0.17205038]
  [0.03447446 0.58538341 0.3833533 ]
  [0.09179329 0.39121894 0.64141235]]

 [[0.07084741 0.19879093 0.65340797]
  [0.06143885 0.79871854 0.40214025]
  [0.63721393 0.74088641 0.2178443 ]]

 [[0.89808881 0.15216053 0.00735349]
  [0.21166635 0.67404909 0.5004432 ]
  [0.70232832 0.58510388 0.34657784]]]


In [13]:
# Replace all odd numbers in arr with -1
# your code here
#pass
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print("Arreglo con números impares reemplazados por -1:")
print(arr)


Arreglo con números impares reemplazados por -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# Create an array of type float
#pass
arreglo_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

print("Arreglo de tipo float:")
print(arreglo_float)

Arreglo de tipo float:
[1.1 2.2 3.3 4.4 5.5]


In [15]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
#pass
arreglo_1d = np.array([1, 2, 3, 4, 5, 6])
arreglo_2d = arreglo_1d.reshape(2, -1)

print("Arreglo bidimensional con 2 filas:")
print(arreglo_2d)

Arreglo bidimensional con 2 filas:
[[1 2 3]
 [4 5 6]]


In [16]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
#pass
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
valores_comunes = np.intersect1d(Z1, Z2)

print("Valores comunes entre Z1 y Z2:")
print(valores_comunes)


Valores comunes entre Z1 y Z2:
[0 2 5 6 7 8]


In [17]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
#pass
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
son_iguales = np.array_equal(A, B)

if son_iguales:
    print("Los arreglos A y B son iguales.")
else:
    print("Los arreglos A y B no son iguales.")

Los arreglos A y B no son iguales.


In [18]:
# Stack arrays a and b vertically
# your code here
#pass
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.vstack((a, b))

print("Arreglos apilados verticalmente:")
print(resultado)

Arreglos apilados verticalmente:
[[1 2 3]
 [4 5 6]]


In [19]:
# Stack the arrays a and b horizontally.
# your code here
#pass
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.hstack((a, b))

print("Arreglos apilados horizontalmente:")
print(resultado)


Arreglos apilados horizontalmente:
[1 2 3 4 5 6]


In [20]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
# pass
elementos_entre_5_y_10 = tmp[(tmp >= 5) & (tmp <= 10)]

print("Elementos entre 5 y 10 del arreglo tmp:")
print(elementos_entre_5_y_10)

Elementos entre 5 y 10 del arreglo tmp:
[ 5  6  7  8  9 10]
