<a href="https://colab.research.google.com/github/ginaazambrano/IA2023-2GINA_ZAMBRANO/blob/main/cuadernog_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create an array with random values between 1 and 10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(3, 4))

# Print the random array
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[9 5 9 7]
 [2 4 2 1]
 [2 1 8 7]]
[[ 3  9 10  8]
 [10  8  5  1]
 [ 7  7  8 10]]
(3, 4)
(3, 4)
adding numbers
[[12 14 19 15]
 [12 12  7  2]
 [ 9  8 16 17]]
substracting numbers
[[ 6 -4 -1 -1]
 [-8 -4 -3  0]
 [-5 -6  0 -3]]
multiply numbers
[[27 45 90 56]
 [20 32 10  1]
 [14  7 64 70]]
[[12 14 19 15]
 [12 12  7  2]
 [ 9  8 16 17]]
[[27 45 90 56]
 [20 32 10  1]
 [14  7 64 70]]
[[3.         0.55555556 0.9        0.875     ]
 [0.2        0.5        0.4        1.        ]
 [0.28571429 0.14285714 1.         0.7       ]]


In [2]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))
print(a.shape)

[[8 1 2]
 [6 1 3]]
[[9 7 7 3]
 [7 6 5 4]
 [3 2 6 1]]
[[85 66 73 30]
 [70 54 65 25]]
[[85 66 73 30]
 [70 54 65 25]]
(2, 3)


In [3]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[9 2]
 [5 2]]
[[9 5]
 [2 2]]


In [4]:
a = np.random.randint(1, 11, size=(4,3))
b = np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('---------------')
print(c)

(4, 3)
(3,)
[[4 2 2]
 [8 8 5]
 [8 2 6]
 [7 2 4]]
[1 0 2]
(4, 3)
---------------
[[9 5 9]
 [7 2 4]
 [2 1 2]
 [1 8 7]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b

  print(a)
  print(b)
  print(c)

  c=a+b
  print(c)

[[4 2 2]
 [8 8 5]
 [8 2 6]
 [7 2 4]]
[1 0 2]
[[5 2 4]
 [7 2 4]
 [2 1 2]
 [1 8 7]]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]
[[4 2 2]
 [8 8 5]
 [8 2 6]
 [7 2 4]]
[1 0 2]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]
[[4 2 2]
 [8 8 5]
 [8 2 6]
 [7 2 4]]
[1 0 2]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]
[[4 2 2]
 [8 8 5]
 [8 2 6]
 [7 2 4]]
[1 0 2]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]
[[5 2 4]
 [9 8 7]
 [9 2 8]
 [8 2 6]]


In [6]:
a=np.array([1,2,3])

print(a)
tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
a=np.random.randint(0,10, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)
print(a.mean(axis=1))

[[3 2 3 1 2 2]
 [2 5 5 5 9 3]
 [0 6 2 0 0 3]
 [3 9 1 6 4 2]
 [2 3 9 3 6 7]
 [7 2 2 0 2 2]]
3.4166666666666665
[2.16666667 4.83333333 1.83333333 4.16666667 5.         2.5       ]
