<a href="https://colab.research.google.com/github/ginaazambrano/IA2023-2GINA_ZAMBRANO/blob/main/cuader_Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#create an array with random inteher values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('Adding numbers')
#plus
print(a+b)
print('Subtracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)


print('Add')
print(np.add(a,b))
print('Substract')
print(np.multiply(a,b))
print('Multiply')
print(np.subtract(a,b))
print('Divide')
print(np.divide(a,b))

[[ 6  3  6  4]
 [ 7  7  4  7]
 [ 1 10  1  9]]
[[3 6 5 7]
 [7 3 3 7]
 [6 8 8 7]]
(3, 4)
(3, 4)
Adding numbers
[[ 9  9 11 11]
 [14 10  7 14]
 [ 7 18  9 16]]
Subtracting numbers
[[ 3 -3  1 -3]
 [ 0  4  1  0]
 [-5  2 -7  2]]
Multiplication numbers
[[18 18 30 28]
 [49 21 12 49]
 [ 6 80  8 63]]
Add
[[ 9  9 11 11]
 [14 10  7 14]
 [ 7 18  9 16]]
Substract
[[18 18 30 28]
 [49 21 12 49]
 [ 6 80  8 63]]
Multiply
[[ 3 -3  1 -3]
 [ 0  4  1  0]
 [-5  2 -7  2]]
Divide
[[2.         0.5        1.2        0.57142857]
 [1.         2.33333333 1.33333333 1.        ]
 [0.16666667 1.25       0.125      1.28571429]]


In [2]:
m1 = np.random.randint(1, 11, size=(3,4))
m2 = np.random.randint(1, 11, size=(4,8))
print('Matriz 1')
print(m1)
print(m1.shape)
print('Matriz 2')
print(m2)
print(m2.shape)
print('-------------------------')
print('Forma 1')
print(np.dot(m1,m2))
print('Forma 2')
print(m1.dot(m2))
print(np.dot(m1,m2).shape)

Matriz 1
[[ 1  1  1  9]
 [10 10  9  9]
 [10  6 10  7]]
(3, 4)
Matriz 2
[[ 4 10  3  4  4  1  2  3]
 [ 6  6 10  2  3  2  6 10]
 [ 3  1  7  7  6  2  7  7]
 [ 5  7 10  2  3  3  1  4]]
(4, 8)
-------------------------
Forma 1
[[ 58  80 110  31  40  32  24  56]
 [172 232 283 141 151  75 152 229]
 [141 195 230 136 139  63 133 188]]
Forma 2
[[ 58  80 110  31  40  32  24  56]
 [172 232 283 141 151  75 152 229]
 [141 195 230 136 139  63 133 188]]
(3, 8)


In [3]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[10  4]
 [ 1  1]]
[[10  1]
 [ 4  1]]


In [4]:
#broadcast
x = np.random.randint(1, 11, size=(4,3))
y = np.array([1,0,2])

print(x.shape)
print(y.shape)

z=np.empty_like(x)
print('---------------------')
print(x)
print('---------------------')
print(y)
print(z.shape)
print('---------------------')
print(z)

(4, 3)
(3,)
---------------------
[[ 4  5  1]
 [ 1  7  4]
 [ 9  7  3]
 [ 5  4 10]]
---------------------
[1 0 2]
(4, 3)
---------------------
[[4611686018427387904 4602678819172646912 4608083138725491507]
 [4603322190547985554 4607182418800017408 4612436618365282987]
 [4608683618675807573 4607182418800017408 4595172819793696085]
 [4608308318706860032 4593671619917905920 4608469161550694693]]


In [5]:
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[ 5  5  3]
 [ 2  7  6]
 [10  7  5]
 [ 6  4 12]]


In [6]:
z=x+y
print(z)


[[ 5  5  3]
 [ 2  7  6]
 [10  7  5]
 [ 6  4 12]]


In [7]:
#para comentar varias lineas de codigo se usa triple comillas simples """  """

a=np.array([1,2,3])
print(a)
print('-----------------')

b = np.full((6,3),[a])
print(b)
print('-----------------')

c= np.tile(a,(6,1))
print(c)


[1 2 3]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
m1 = np.random.randint(0, 10, size=(6,6))
print(m1)
aux=np.mean(m1)
print(aux)

np.mean(m1, axis=1) #promedio por filas
np.mean(m1, axis=0) #promedio por filas

print('Promedio por filas')
print(np.mean(m1, axis=1))
print('Promedio por columnas')
print(np.mean(m1, axis=0))

[[1 2 7 2 8 9]
 [6 1 9 7 4 7]
 [3 5 2 1 0 3]
 [2 8 5 6 2 5]
 [2 1 7 7 2 8]
 [2 7 6 6 7 2]]
4.5
Promedio por filas
[4.83333333 5.66666667 2.33333333 4.66666667 4.5        5.        ]
Promedio por columnas
[2.66666667 4.         6.         4.83333333 3.83333333 5.66666667]
