<a href="https://colab.research.google.com/github/ginaazambrano/IA2023-2GINA_ZAMBRANO/blob/main/cuaderno_g_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
aux=np.array([1,2,3,4,5])
print(aux)
print(aux.shape)

aux2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(aux2)
print(aux2.shape)
print(type(aux2))

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
<class 'numpy.ndarray'>


In [3]:
tmp=np.zeros((4,4))
print(tmp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
print("Matriz full valores del mismo numeroi")
tmp=np.full((4,4),5)
print(tmp)

Matriz full valores del mismo numeroi
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [5]:
print("Matriz diagonal")
tmp=np.eye(4,4)
print(tmp)

Matriz diagonal
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
print("Matriz de 1")
tmp=np.ones((4,4))
print(tmp)

Matriz de 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[1.70045539 0.47536262 1.37526943 3.59718189]
 [8.00182793 8.7882254  2.52169645 3.22848801]
 [8.9535313  3.80692462 4.18540015 7.74629106]
 [2.63363483 6.32646946 9.13583979 5.6867211 ]]
(4, 4)


In [8]:
print(tmp[:2,:2])

[[1.70045539 0.47536262]
 [8.00182793 8.7882254 ]]


In [9]:
print(tmp[3])

[2.63363483 6.32646946 9.13583979 5.6867211 ]


In [10]:
print(tmp[2,2])


4.185400148130122


In [11]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)


Numeros randoms
[[6.67203142 9.6507126  6.84550257 4.55975011]
 [5.77764282 1.44206288 6.1850285  1.48990523]
 [5.05795937 7.91371725 0.10676035 0.23407169]
 [7.17009705 0.17066854 2.30675191 1.82277083]]
(4, 4)


In [12]:
mask=tmp>5
print(tmp[mask])

[6.67203142 9.6507126  6.84550257 5.77764282 6.1850285  5.05795937
 7.91371725 7.17009705]
