<a href="https://colab.research.google.com/github/ginaazambrano/IA2023-2GINA_ZAMBRANO/blob/main/cuadern_de_Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as gina

aux=gina.array([1,2,4,5])
print(aux)
# Tipo de arreglo
print(aux.shape)
print('------------------------------')

aux=gina.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('------------------------------')

tmp=gina.zeros((4,4))
print(tmp)
print('------------------------------')


tmp=gina.full((4,4),5)
print(tmp)
print('------------------------------')


tmp=gina.eye(4,4)
print(tmp)
print('------------------------------')


tmp=gina.ones((4,4))
print(tmp)
print('------------------------------')

[1 2 4 5]
(4,)
------------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------


In [3]:
tmp=10*gina.random.random((4,4))
print(tmp)
print('------------------------------')

[[7.27345084 7.30091169 6.71733252 0.6520065 ]
 [1.22280201 4.54360589 5.11675369 6.93349556]
 [1.39092732 0.96220153 1.25275133 6.91517021]
 [6.98596505 8.60664207 0.83825849 1.28434977]]
------------------------------


In [4]:
print(tmp[:2,:2])
print('------------------------------')
print(tmp[2:4,2:4])

[[7.27345084 7.30091169]
 [1.22280201 4.54360589]]
------------------------------
[[1.25275133 6.91517021]
 [0.83825849 1.28434977]]


In [5]:
print(tmp[1,1])
print('------------------------------')
print(tmp[2,2])
print('------------------------------')

4.543605888758789
------------------------------
1.2527513320194417
------------------------------


In [6]:
tmp=10*gina.random.random((4,4))
print(tmp)

[[3.47528378 5.39969257 6.73105109 1.31744624]
 [1.92235633 8.35292947 7.03532081 8.23777889]
 [8.10450913 7.00787051 7.78833246 7.89908983]
 [3.35327867 3.4651379  3.25619457 2.41717647]]


In [7]:
mascara=tmp>5
print(mascara)
print('------------------------------')
print(tmp[mascara])
print('------------------------------')


[[False  True  True False]
 [False  True  True  True]
 [ True  True  True  True]
 [False False False False]]
------------------------------
[5.39969257 6.73105109 8.35292947 7.03532081 8.23777889 8.10450913
 7.00787051 7.78833246 7.89908983]
------------------------------


In [8]:

mask = (tmp >=2) & (tmp<=4)
print(tmp[mask])


[3.47528378 3.35327867 3.4651379  3.25619457 2.41717647]


In [9]:
tmp = gina.random.randint(0, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = gina.mod(tmp, 2) == 0
print(tmp[mask])

[[3 2 7 4]
 [7 6 9 1]
 [0 6 9 0]
 [4 7 4 2]]
----------------------------------
[2 4 6 0 6 0 4 4 2]
