<a href="https://colab.research.google.com/github/ginaazambrano/IA2023-2GINA_ZAMBRANO/blob/main/NUMPY%20_Ejercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

# Check the NumPy version
print(np.__version__)


1.23.5


In [3]:
# Create a 1D array of numbers from 0 to 9
array_1d = np.arange(10)

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)



Random vector with the maximum value replaced by 0:
[0.70619512 0.19323784 0.         0.22205659 0.27062126 0.89460492
 0.47479591 0.45221804 0.1124071  0.76204301]


In [5]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# To print the number 8
number_to_find = 8

indices = np.where(arr == number_to_find)

print("Indices of the number 8:")
print(indices)

found_value = arr[indices]
print("The number 8 is at position:", indices[0], indices[1])
print("Value at that position:", found_value)


Indices of the number 8:
(array([1]), array([2]))
The number 8 is at position: [1] [2]
Value at that position: [8]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use slicing to extract the numbers [3, 4, 5]
subset = arr[2:5]

print("The numbers [3, 4, 5] from the array:")
print(subset)


The numbers [3, 4, 5] from the array:
[3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use slicing to extract the last 4 numbers
a = arr[-4:]

print("The last 4 numbers from the array:")
print(a)


The last 4 numbers from the array:
[4 5 6 7]


In [8]:
t = np.ones((2, 2), dtype=bool)

print(t)

[[ True  True]
 [ True  True]]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to extract odd numbers
odd_numbers = arr[arr % 2 == 1]

print("Odd numbers from the array:")
print(odd_numbers)


Odd numbers from the array:
[1 3 5 7 9]


In [10]:
vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
random_array = np.random.randint(0, 101, size=(10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[ 60  60  68  95  27  63  17  90  37  57]
 [ 78  82  65  84  98  41  64  61  89  71]
 [ 46  72   6  66  60  38  26  23  99   2]
 [ 65  31  58  23  30  13   3  36  49   2]
 [  4   8  10  46  68  77  19  39  92  53]
 [100  11  12   5  68  93  67  95  63  52]
 [ 61  68  44  48  14  27  50  54  59  60]
 [ 92  35  51  70  69  66  56  76  25  25]
 [ 87   5  51  29  79  71  28   6  61  54]
 [ 80  55  84  83  67  19   6  66   9  60]]
Minimum Value: 2
Maximum Value: 100


In [13]:
randon = np.random.rand(3, 3, 3)

print(randon)

[[[0.72137477 0.78752792 0.16800761]
  [0.77193954 0.45071658 0.27750407]
  [0.94854368 0.1138582  0.48483552]]

 [[0.23452393 0.08285267 0.3673898 ]
  [0.37216871 0.25542457 0.82702762]
  [0.3818931  0.80941675 0.07465142]]

 [[0.43687448 0.67117798 0.06551144]
  [0.8022313  0.41110699 0.81694086]
  [0.17143687 0.48957802 0.77316287]]]


In [14]:
import numpy as np

# Create or define your NumPy array (arr)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to replace odd numbers with -1
arr[arr % 2 == 1] = -1

print("Modified array with odd numbers replaced by -1:")
print(arr)

Modified array with odd numbers replaced by -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [15]:
float_array = np.array([1.3, 2.5, 3.7, 4.2])

print(float_array)

[1.3 2.5 3.7 4.2]


In [16]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the 1D array into a 2D array with 2 rows
arr_2d = arr_1d.reshape(2, -1)

print("1D Array:")
print(arr_1d)

print("2D Array with 2 rows:")
print(arr_2d)


1D Array:
[1 2 3 4 5 6 7 8]
2D Array with 2 rows:
[[1 2 3 4]
 [5 6 7 8]]


In [17]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Find the common values between Z1 and Z2
common_values = np.intersect1d(Z1, Z2)

print("Array Z1:", Z1)
print("Array Z2:", Z2)
print("Common values:", common_values)

Array Z1: [6 6 0 6 2 4 5 8 8 0]
Array Z2: [4 1 6 5 4 6 7 6 2 1]
Common values: [2 4 5 6]


In [18]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [1 0 1 0 1]
Array B: [0 0 0 0 0]
Are A and B equal? False


In [19]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])

# Stack arrays a and b vertically
stacked_array = np.vstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (vertically):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (vertically):
[[0 2 5]
 [0 2 5]]


In [20]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])

# Stack arrays a and b horizontally
stacked_array = np.hstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (horizontally):")
print(stacked_array)


Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (horizontally):
[0 2 5 0 2 5]


In [21]:

tmp = np.arange(15)

# Create a boolean mask to identify elements between 5 and 10
mask = (tmp >= 5) & (tmp <= 10)

# Use the boolean mask to extract elements between 5 and 10
result = tmp[mask]

print("Array tmp:")
print(tmp)

print("Items between 5 and 10:")
print(result)

Array tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Items between 5 and 10:
[ 5  6  7  8  9 10]


In [22]:
def pair_max(a, b):
    """Get the element-wise maximum of two arrays a and b."""
    return np.maximum(a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)


[6 7 9 8 9 7 5]


In [23]:
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array after swapping columns 1 and 2:")
print(arr)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after swapping columns 1 and 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [24]:
random_array = np.random.uniform(5, 10, size=(5, 3))

print(random_array)


[[6.99991562 7.85582775 5.65559694]
 [5.18921101 8.5955184  5.69458638]
 [8.02841884 5.35333334 6.13251655]
 [9.51049035 9.06951219 7.55559833]
 [5.94537028 7.54493392 6.72596289]]
